import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React, {useState, useEffect} from "react"
import LinkerButton from "../components/linker-button"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [topTracks, setTopTracks] = useState<any[]>([]);
 
  const fetchTopTracks = async () => {
    const response = await fetch("/api/stats/top-tracks");
    const data = await response.json();
    // const tracksArray = JSON.parse(data.tracks);
    setTopTracks(data);
    console.log(data);
  };

  useEffect(() => {
    fetchTopTracks();

    return () => {
      <div></div>
    }
  }, [])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>Welcome to Obscure Music Recs</h1>
          <h3>We get it, you want good music taste</h3>
          <LinkerButton href="/playlists" children="Click Here To Get Started"></LinkerButton>
          {/* <ul>
            {topTracks.tracks?.map((tracks:any) => {
              return (
                <li>
                  {tracks.title}
                </li>
              );
            })}
          </ul> */}
        </div>
      </main>
    </>
  )
}
